# 3. Heterogeneity Computations
The goal in this notebook is to generate estimates of heterogeneity by computing $I^2$, the proportion between-study variance due to heterogeneity rather than random sampling error. We compute this via simulation. Should be run after the Stan model is run, but before the visuals are generated.

In [1]:
library(tidyverse)
library(ggplot2)
library(rstan)
library(Hmisc)
set.seed(20)

Warning message:
"package 'tidyverse' was built under R version 4.3.3"
── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.2.1
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.2
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors
Loading required package: StanHeaders


rstan version 2.32.5 (Stan version 2.32.2)


For execution on a local, multicore CPU with excess RAM we recommend calling
options(mc.cores = parallel::detectCores()).
To avoid recompilation of unchanged Stan programs, we recommend calling
rstan_options(auto_write = TRUE)
For within-chain threading using `reduce_sum()` or `map_rect()` Stan functions,
change `threads_per_chain` option:
rstan_options(threads_per_chain = 1)


Do not specify '-march=native' in 'LOCAL_CPPFLAGS' or a Makevars file


Attaching package: 'rstan'


The following object is masked from 'package:tidyr':

    extract



Attaching package: 'Hmisc'


The following objects are masked from 'package:dplyr':

    src, summarize


The following objects are masked from 'package:base':

    format.pval, units

In [2]:
inv_logit = plogis
logit = qlogis

In [3]:
base_dir = getwd()
io_set = "Main Results"
model_input_dir  = file.path(base_dir, "Processed Data", io_set)
model_output_dir = file.path(base_dir, "Model Output", io_set)
output_dir = file.path(base_dir, "Heterogeneity Estimates", io_set)

#sev_class_type = "1997type"
#sev_class_type = "2009type"
sev_class_type = "hospitalisation"
save_output = TRUE

In [4]:
#Read in the model input data (which gives information on outcomes and scenarios)
input_data = file.path(model_input_dir, paste0("data_", sev_class_type, ".rds")) %>% readRDS

#Read in the model results. We are primarily interested in the pooled estimates p and the outcome estimates theta
model_results = file.path(model_output_dir, paste0("Results_LogisticRegression_mean=0_sd=2_sd_mean=0.5_sdsd=2_", sev_class_type, ".rds")) %>% readRDS

In [5]:
#Extract some variables from input data to get correct indices on things
scenario_df = input_data$scenario_df
outcome_df = input_data$outcome_df %>% mutate(ThetaIndex = 1:nrow(.))

#Get the reference region and the non-reference one
ref_region = input_data$ref_region
non_ref_region = ifelse(ref_region == "Asia", "Americas", "Asia")
ref_serotype_exposure = input_data$ref_serotype_exposure #Get reference serotype-prior exposure combination
ref_scenario = input_data$ref_scenario #Get reference scenario
non_ref_seroprior = input_data$char_mat_guide %>% filter(CharMatIndex >0) %>% pull(SeroPriorExp) %>% as.character #Get all non-reference serotype-prior exposures

#Get scenario labels ordered according to the model output which gives the reference scenario, then all non-reference serotype prior exposures in the reference region,
#followed by the reference serotype-exposure in the non-reference region, and the rest of the serotype-prior exposures in the non-reference region
scenario_labels = c(ref_scenario, 
                    paste0(ref_region, "-", non_ref_seroprior),
                    paste0(non_ref_region, "-", c(ref_serotype_exposure, non_ref_seroprior))
                   )

#Add these indices to the scenario DataFrame from the model input
scenario_p_matcher = data.frame(Scenario = scenario_labels) %>% mutate(ScenarioIndex = 1:nrow(.))
scenario_df = scenario_df %>% left_join(scenario_p_matcher, by = "Scenario")
scenario_df

   SeroPriorExp    Region   Scenario                 NumStudies Severe
1  Unknown-DENV1   Americas Americas-Unknown-DENV1   7          7496
2  Unknown-DENV2   Americas Americas-Unknown-DENV2   6          1326
3  Unknown-DENV3   Americas Americas-Unknown-DENV3   3          1770
4  Unknown-DENV4   Americas Americas-Unknown-DENV4   2          2011
5  Primary-DENV1   Americas Americas-Primary-DENV1   0             0
6  Primary-DENV2   Americas Americas-Primary-DENV2   0             0
7  Primary-DENV3   Americas Americas-Primary-DENV3   0             0
8  Primary-DENV4   Americas Americas-Primary-DENV4   0             0
9  Secondary-DENV1 Americas Americas-Secondary-DENV1 0             0
10 Secondary-DENV2 Americas Americas-Secondary-DENV2 0             0
11 Secondary-DENV3 Americas Americas-Secondary-DENV3 0             0
12 Secondary-DENV4 Americas Americas-Secondary-DENV4 0             0
13 Unknown-DENV1   Asia     Asia-Unknown-DENV1       5           182
14 Unknown-DENV2   Asia     Asia-Unknown-DENV2       7           299
15 Unknown-DENV3   Asia     Asia-Unknown-DENV3       5           336
16 Unknown-DENV4   Asia     Asia-Unknown-DENV4       3            15
17 Primary-DENV1   Asia     Asia-Primary-DENV1       2             4
18 Primary-DENV2   Asia     Asia-Primary-DENV2       2             1
19 Primary-DENV3   Asia     Asia-Primary-DENV3       2            22
20 Primary-DENV4   Asia     Asia-Primary-DENV4       0             0
21 Secondary-DENV1 Asia     Asia-Secondary-DENV1     2             4
22 Secondary-DENV2 Asia     Asia-Secondary-DENV2     2             7
23 Secondary-DENV3 Asia     Asia-Secondary-DENV3     1             1
24 Secondary-DENV4 Asia     Asia-Secondary-DENV4     0             0
   NonSevere N     Inclusion ScenIndex CharMatIndex ScenarioIndex
1  17413     24909 Included   1         1           11
2   2165      3491 Included   2         2           12
3   2555      4325 Included   3         3           13
4   6218      8229 Included   4         4           14
5      0         0 Excluded  -1         5           15
6      0         0 Excluded  -1         6           16
7      0         0 Excluded  -1         7           17
8      0         0 Excluded  -1        NA           NA
9      0         0 Excluded  -1         8           18
10     0         0 Excluded  -1        -1           10
11     0         0 Excluded  -1        NA           NA
12     0         0 Excluded  -1        NA           NA
13   369       551 Included   5         1            2
14   500       799 Included   6         2            3
15   783      1119 Included   7         3            4
16    23        38 Included   8         4            5
17    59        63 Included   9         5            6
18    19        20 Included  10         6            7
19    31        53 Included  11         7            8
20     0         0 Excluded  -1        NA           NA
21    47        51 Included  12         8            9
22    32        39 Included  13        -1            1
23    20        21 Excluded  -1        NA           NA
24     0         0 Excluded  -1        NA           NA

In [6]:
#We only generate I^2 estimates for included scenarios (those with at least 2 studies contributing data)
included_scenarios = scenario_df %>% filter(Inclusion == "Included")

#Get the available posterior samples for p and theta
p_est_draws = extract(model_results, pars = "p")$p
theta_est_draws = extract(model_results, pars = "theta")$theta

In [7]:
theta_est_draws

      [,1]         [,2]        [,3]      [,4]      [,5]      [,6]
 [1,] 0.0220361567 0.473827967 0.2179110 0.4776241 0.5447827 0.3487387
 [2,] 0.0054353554 0.063251391 0.2104748 0.4608320 0.5919819 0.3482950
 [3,] 0.0343190383 0.142419577 0.2333995 0.4196006 0.5088506 0.3145338
 [4,] 0.0729926082 0.084301617 0.2201977 0.3189805 0.5707413 0.3402949
 [5,] 0.0116742426 0.013820919 0.2250310 0.3442469 0.5201749 0.3294308
 [6,] 0.0733502214 0.159876584 0.1783119 0.4263967 0.5758592 0.3219949
 [7,] 0.0071231738 0.058966517 0.1986779 0.4711850 0.6660963 0.3672456
 [8,] 0.0119575996 0.162372723 0.1569437 0.3835065 0.5756705 0.3430122
 [9,] 0.0503151915 0.058036260 0.1903953 0.3069982 0.6368655 0.3656543
[10,] 0.0002393563 0.121671767 0.2154224 0.5420303 0.5482209 0.3168748
[11,] 0.0220516172 0.438560460 0.2191368 0.4487820 0.5946929 0.3347930
[12,] 0.0044825153 0.063911819 0.1953939 0.4268006 0.5202401 0.3358904
[13,] 0.0165943523 0.005458214 0.2136723 0.3916909 0.5161208 0.3091268
[14,] 0.0485276638 0.294961043 0.1755347 0.4429377 0.5418073 0.3761799
[15,] 0.0130525525 0.311930810 0.2136534 0.3773374 0.5952046 0.3366072
[16,] 0.0074918741 0.258779930 0.2191471 0.4605462 0.5639532 0.3845567
[17,] 0.0171470046 0.154355789 0.1871450 0.4385207 0.6169087 0.3404362
[18,] 0.0080879103 0.215787838 0.2027773 0.3892542 0.5062030 0.3796166
[19,] 0.0072474925 0.084011190 0.2251053 0.3609325 0.5425784 0.3541872
[20,] 0.0026973367 0.214424072 0.1789256 0.4059074 0.5094082 0.3488932
[21,] 0.0025132626 0.029793703 0.2214906 0.4663611 0.6634391 0.3578369
[22,] 0.0772935741 0.079097432 0.2194642 0.3628833 0.5942967 0.3698672
[23,] 0.0020881287 0.116195603 0.2215409 0.4295837 0.5829325 0.3212272
[24,] 0.0888488434 0.044054053 0.2031269 0.4339698 0.6055067 0.3697164
[25,] 0.0045619268 0.094141197 0.2108572 0.4348998 0.5245297 0.3407649
[26,] 0.0667087195 0.022103919 0.2083220 0.4413720 0.5099944 0.3691959
[27,] 0.0090327932 0.023209140 0.2161946 0.4043668 0.5738005 0.3713276
[28,] 0.0145185970 0.061071806 0.1934024 0.3729242 0.4906978 0.3294459
[29,] 0.0657837374 0.337587930 0.2064318 0.4073864 0.5032685 0.3355352
[30,] 0.0150973804 0.250370004 0.1992567 0.6363162 0.4852917 0.3506257
[31,] ⋮            ⋮           ⋮         ⋮         ⋮         ⋮
[32,] 0.017361151  0.09223263  0.1587161 0.3553725 0.5602293 0.3659649
[33,] 0.004715604  0.04266827  0.2564536 0.4576303 0.6581819 0.3555797
[34,] 0.005658758  0.24022947  0.2312785 0.4077232 0.5959958 0.3228448
[35,] 0.016121970  0.20588590  0.1899872 0.4579720 0.5433799 0.3083306
[36,] 0.031845094  0.10554573  0.2026505 0.4302501 0.5768854 0.2917481
[37,] 0.018036468  0.03952048  0.1934612 0.4333091 0.4935607 0.3581133
[38,] 0.040183902  0.19191974  0.2245738 0.2993758 0.5217260 0.3515235
[39,] 0.002761292  0.04319656  0.2380501 0.3547159 0.5919636 0.3681784
[40,] 0.035588615  0.17683071  0.2193134 0.4021454 0.5877792 0.3795335
[41,] 0.054628304  0.39239536  0.2138290 0.4450449 0.4939386 0.3319986
[42,] 0.062341874  0.10604101  0.2037203 0.5879024 0.6059230 0.3207822
[43,] 0.014439295  0.10189331  0.2075852 0.6198616 0.5257159 0.3372380
[44,] 0.143029782  0.36900183  0.2357309 0.4221182 0.4966858 0.3294250
[45,] 0.022260879  0.01256801  0.2250854 0.4176493 0.6119754 0.3117733
[46,] 0.005197707  0.05826289  0.1673627 0.3783035 0.5368433 0.3512950
[47,] 0.025468783  0.10701070  0.2141337 0.4813075 0.5347520 0.3610773
[48,] 0.003022410  0.01508501  0.1991387 0.3680851 0.5684038 0.3401248
[49,] 0.063292643  0.15176245  0.2249922 0.3560342 0.5634797 0.3381974
[50,] 0.104287534  0.36909330  0.2139230 0.5002905 0.6301942 0.3620112
[51,] 0.031304935  0.07938563  0.2170255 0.2537862 0.4780994 0.3311574
[52,] 0.020559731  0.07354648  0.2020757 0.3383161 0.5249848 0.3699577
[53,] 0.020937813  0.16153584  0.2202868 0.4530496 0.5215981 0.3659461
[54,] 0.021757162  0.07897202  0.2364524 0.4775851 0.5511949 0.3909663
[55,] 0.002208273  0.09966077  0.2524785 0.5036763 0.6121975 0.3469624
[56,] 0.007539088  0.11782486  0.2134665 0.5936285 0.5654729 0.3673325
[57,] 0.024116014  0.01838005  0.2419778 0.5219194 0.6165763 0.3392882
[58,] 0.007958406  0.04603596  0.1890437 0.4050023 0.4721953 0.3400073
[59,] 0.019840624  0.04975593  0.1886903 0.3170349 0.5195228 0.3356471
[60,] 0.004850106  0.32315608  0.1786839 0.3263001 0.6249418 0.3390207
[61,] 0.032779805  0.13445237  0.2241962 0.3844534 0.5383180 0.3476869
      [,7]         [,8]       [,9]      [,10]     [,11] [,12]     [,13]
 [1,] 0.0363741593 0.35188895 0.1177806 0.2715002 ⋯     0.2150550 0.1703246
 [2,] 0.0693941593 0.14170547 0.1204924 0.2614073 ⋯     0.3105355 0.1963598
 [3,] 0.0108766049 0.13152568 0.1175414 0.2480286 ⋯     0.2182407 0.1587239
 [4,] 0.1440922437 0.12871236 0.1156797 0.2535150 ⋯     0.2283157 0.1818796
 [5,] 0.0309044817 0.14303889 0.1091507 0.2669381 ⋯     0.1473206 0.1881287
 [6,] 0.0695305898 0.14079924 0.1184680 0.2320678 ⋯     0.2052843 0.1688061
 [7,] 0.0489570516 0.07123082 0.1158916 0.2454942 ⋯     0.1847117 0.1929242
 [8,] 0.1428215322 0.07028524 0.1149666 0.2370563 ⋯     0.3097811 0.1721595
 [9,] 0.1428970715 0.34050531 0.1132881 0.2508128 ⋯     0.4668923 0.2035021
[10,] 0.0017748742 0.12076759 0.1189246 0.2557737 ⋯     0.2653999 0.2194329
[11,] 0.0372078704 0.06253160 0.1189453 0.2673369 ⋯     0.3038745 0.1816569
[12,] 0.0653738961 0.11134230 0.1108922 0.2560696 ⋯     0.2038891 0.1061678
[13,] 0.0279559784 0.07131072 0.1154989 0.2672262 ⋯     0.1953010 0.1974904
[14,] 0.1349318441 0.19388133 0.1163401 0.2515947 ⋯     0.2659871 0.1936751
[15,] 0.0578424379 0.10016935 0.1150943 0.2550028 ⋯     0.2882175 0.1705642
[16,] 0.0532544044 0.17658916 0.1187884 0.2600632 ⋯     0.3077763 0.1819705
[17,] 0.0006379162 0.20288032 0.1162441 0.2556601 ⋯     0.2375877 0.1702362
[18,] 0.0153426582 0.12403020 0.1216571 0.2190978 ⋯     0.1577554 0.2219148
[19,] 0.0048363867 0.20376153 0.1152767 0.2375682 ⋯     0.2212327 0.1358562
[20,] 0.0078731012 0.15284538 0.1195009 0.2581988 ⋯     0.2900895 0.2133454
[21,] 0.1228606701 0.11836788 0.1095299 0.2386328 ⋯     0.2647522 0.1593177
[22,] 0.0025177373 0.04370625 0.1177325 0.2438234 ⋯     0.3446161 0.1731791
[23,] 0.0233854251 0.11145658 0.1163564 0.2475950 ⋯     0.3232197 0.1600122
[24,] 0.0691599706 0.13471740 0.1176740 0.2387054 ⋯     0.2185369 0.1668701
[25,] 0.0061390058 0.07836302 0.1102857 0.2515082 ⋯     0.2086724 0.1594662
[26,] 0.0044872615 0.10883125 0.1122039 0.2695580 ⋯     0.2015034 0.1556689
[27,] 0.0318764500 0.16730936 0.1189997 0.2660106 ⋯     0.2684880 0.1790860
[28,] 0.0254619108 0.35928028 0.1232830 0.2597325 ⋯     0.2739351 0.1165217
[29,] 0.0649773883 0.08934892 0.1163068 0.2440037 ⋯     0.2665799 0.1206146
[30,] 0.1309345808 0.07759812 0.1098398 0.2695620 ⋯     0.2980604 0.1775896
[31,] ⋮            ⋮          ⋮         ⋮         ⋱     ⋮         ⋮
[32,] 1.626736e-02 0.11824586 0.1190644 0.2475553 ⋯     0.1683269 0.19831288
[33,] 2.273077e-02 0.24709140 0.1166880 0.2627543 ⋯     0.1893783 0.14749849
[34,] 2.160494e-02 0.15741612 0.1202160 0.2563707 ⋯     0.1874179 0.19986225
[35,] 5.497865e-02 0.08252217 0.1147856 0.2438501 ⋯     0.2218559 0.22752582
[36,] 5.953825e-02 0.04358637 0.1200061 0.2650475 ⋯     0.3255735 0.20676078
[37,] 4.397488e-07 0.10850180 0.1140465 0.2526325 ⋯     0.2096071 0.21591009
[38,] 9.941568e-04 0.22047116 0.1135862 0.2669759 ⋯     0.1648838 0.17180313
[39,] 1.083029e-02 0.17050981 0.1187220 0.2498088 ⋯     0.3282055 0.13028018
[40,] 5.625758e-04 0.09180549 0.1094392 0.2556052 ⋯     0.2637642 0.14659868
[41,] 2.824391e-02 0.38179335 0.1152794 0.2423980 ⋯     0.1918746 0.21671569
[42,] 1.488837e-02 0.14637272 0.1175890 0.2589884 ⋯     0.1991592 0.18176731
[43,] 1.151857e-02 0.10091863 0.1145914 0.2528727 ⋯     0.3818820 0.19214429
[44,] 6.054276e-02 0.07975078 0.1185128 0.2620632 ⋯     0.2477544 0.15462474
[45,] 3.009925e-02 0.20206808 0.1166525 0.2305743 ⋯     0.1649884 0.23394777
[46,] 4.068873e-02 0.19774917 0.1213673 0.2606446 ⋯     0.2523949 0.21235611
[47,] 1.766225e-01 0.12669064 0.1176984 0.2627175 ⋯     0.1998238 0.16732309
[48,] 3.870615e-02 0.24465945 0.1123185 0.2614516 ⋯     0.2722317 0.19920521
[49,] 2.863498e-02 0.13957654 0.1215486 0.2621071 ⋯     0.2469928 0.15172628
[50,] 9.244540e-02 0.14702568 0.1259275 0.2480164 ⋯     0.2748197 0.17424615
[51,] 5.808242e-02 0.16045994 0.1190531 0.2476015 ⋯     0.1955605 0.19359050
[52,] 1.351528e-03 0.32627408 0.1180027 0.2254538 ⋯     0.3210911 0.19699803
[53,] 1.181627e-02 0.05602637 0.1196452 0.2717573 ⋯     0.1494846 0.17022727
[54,] 7.831121e-02 0.06030197 0.1111167 0.2533105 ⋯     0.2487417 0.17937180
[55,] 2.254286e-03 0.11066957 0.1100769 0.2530167 ⋯     0.2314715 0.17325547
[56,] 7.059464e-03 0.12806057 0.1123857 0.2370421 ⋯     0.2648527 0.14246083
[57,] 9.805127e-02 0.07155255 0.1198007 0.2889264 ⋯     0.2544998 0.19837922
[58,] 7.637623e-05 0.27851185 0.1122695 0.2426577 ⋯     0.1914564 0.13570244
[59,] 2.226523e-02 0.19245034 0.1193471 0.2563090 ⋯     0.2059969 0.07388129
[60,] 1.939059e-04 0.15770338 0.1151457 0.2258033 ⋯     0.2183314 0.11907629
[61,] 3.943887e-02 0.10210141 0.1117793 0.2591416 ⋯     0.3416532 0.13369203
      [,14]     [,15]       [,16]      [,17]       [,18]        [,19]
 [1,] 0.3536027 0.008603057 0.35730678 0.025760248 0.009493648  6.174700e-02
 [2,] 0.2216009 0.115559157 0.04659935 0.042765308 0.083890749  5.083315e-02
 [3,] 0.3685037 0.112336071 0.45636480 0.045157821 0.021251678  6.089574e-02
 [4,] 0.2685083 0.330186814 0.13544909 0.046089487 0.022390183  4.790156e-02
 [5,] 0.4111295 0.003624510 0.23149911 0.050658101 0.077278960  3.545835e-04
 [6,] 0.3499586 0.022675778 0.09020836 0.094180541 0.070992222  2.972635e-02
 [7,] 0.4036221 0.014273844 0.08356558 0.078220934 0.004629907  2.174838e-02
 [8,] 0.3246217 0.029285333 0.10579334 0.056024750 0.025634995  6.566806e-02
 [9,] 0.2894088 0.039070567 0.05407580 0.031152578 0.031286744  1.865517e-02
[10,] 0.4657941 0.096742115 0.34204157 0.076021929 0.039869775  1.951875e-01
[11,] 0.3120919 0.165516274 0.03693205 0.059791715 0.128191872  5.204657e-04
[12,] 0.3875272 0.022084509 0.09223644 0.024267877 0.011646440  5.978726e-02
[13,] 0.2847294 0.033458020 0.09644030 0.056861389 0.072616858  1.528784e-02
[14,] 0.2726667 0.130879638 0.26872156 0.079048085 0.059707802  7.895982e-04
[15,] 0.3041525 0.044827435 0.03688819 0.058902126 0.001440070  6.006200e-03
[16,] 0.3406185 0.070544802 0.12380081 0.076774669 0.044066441  1.648081e-03
[17,] 0.2115584 0.018633888 0.03652276 0.042976844 0.023023626  1.752579e-04
[18,] 0.3190579 0.257979995 0.23422355 0.018773264 0.070862845  3.358788e-02
[19,] 0.3644502 0.044728523 0.27962743 0.021726280 0.043882651  4.291894e-02
[20,] 0.2933141 0.089882769 0.04215316 0.011668316 0.018108874  1.349777e-01
[21,] 0.3311391 0.018169016 0.05607551 0.059043280 0.222301130  2.870627e-02
[22,] 0.3317751 0.021151567 0.06560894 0.038362573 0.011853688  6.890093e-03
[23,] 0.2572366 0.042232853 0.06337514 0.046366713 0.011954253  1.429478e-01
[24,] 0.3490539 0.323947574 0.23941280 0.084930062 0.016598042  9.487842e-04
[25,] 0.3255869 0.154911615 0.18175221 0.094125650 0.002820038  2.413512e-04
[26,] 0.3370133 0.308355133 0.20558313 0.064799148 0.001577333  2.477195e-02
[27,] 0.3503563 0.082915134 0.18529017 0.008555372 0.024240887  2.741722e-02
[28,] 0.3353431 0.129116471 0.04427632 0.039984440 0.029404031  5.752980e-03
[29,] 0.3004088 0.007175709 0.04628192 0.094848889 0.019570318  2.656504e-05
[30,] 0.2822230 0.020311472 0.06068510 0.048531661 0.003777353  7.860622e-03
[31,] ⋮         ⋮           ⋮          ⋮           ⋮            ⋮
[32,] 0.3246720 0.133169787 0.30003487 0.05117435  1.911813e-06 0.0366746563
[33,] 0.3190922 0.107660525 0.18897998 0.05292505  9.316998e-02 0.0538436526
[34,] 0.3803404 0.011891277 0.30683407 0.02102939  2.782744e-02 0.0558603677
[35,] 0.2743557 0.133853179 0.06323446 0.04209990  1.322696e-02 0.0243101752
[36,] 0.4952647 0.097848426 0.16399156 0.05475072  5.791321e-02 0.0030817351
[37,] 0.3929455 0.022962689 0.11970171 0.05910473  6.225059e-03 0.0009770639
[38,] 0.3584372 0.183065021 0.46045137 0.03061846  4.765084e-02 0.0457245068
[39,] 0.3908826 0.287393440 0.10360528 0.10750908  2.689045e-02 0.0060148814
[40,] 0.4826005 0.080762686 0.07421383 0.05719673  1.025111e-02 0.0036037679
[41,] 0.2070820 0.163506251 0.22407932 0.07111687  8.850641e-02 0.0297631472
[42,] 0.3629466 0.166101018 0.28946955 0.03525593  9.630278e-02 0.0010734896
[43,] 0.3576492 0.457796503 0.20149589 0.08088551  3.780739e-02 0.0050222312
[44,] 0.3439888 0.056848273 0.10799086 0.09172199  1.574676e-01 0.0002180932
[45,] 0.2865715 0.470247756 0.52501562 0.01529693  1.688002e-02 0.0014245238
[46,] 0.3737074 0.461752432 0.17285366 0.03221924  1.815299e-02 0.0011662149
[47,] 0.2921910 0.006361434 0.12542620 0.04042047  8.271726e-02 0.0319412494
[48,] 0.3543897 0.120678828 0.14420894 0.06201118  3.749883e-03 0.0088296777
[49,] 0.2921573 0.044041633 0.33621949 0.06001441  1.644872e-03 0.0564216077
[50,] 0.2892024 0.005108154 0.04002627 0.04746834  3.186987e-02 0.0506786518
[51,] 0.4076450 0.030926261 0.03263700 0.02164688  1.406176e-02 0.0317150027
[52,] 0.3220070 0.109669943 0.09152236 0.03389476  8.052231e-03 0.0033049823
[53,] 0.4100015 0.028446962 0.07454905 0.02616065  2.205671e-02 0.0085833438
[54,] 0.3330822 0.021091452 0.03728068 0.01562580  9.923975e-03 0.0388756022
[55,] 0.3682103 0.381198848 0.45532183 0.03639776  1.727282e-01 0.0002766601
[56,] 0.2875338 0.402718059 0.39899571 0.08561708  7.967231e-02 0.0274935020
[57,] 0.3283154 0.015096660 0.23913938 0.06492932  8.584754e-02 0.0262457681
[58,] 0.3202635 0.227488479 0.11830326 0.08143519  2.692863e-02 0.0303320005
[59,] 0.3022872 0.348063326 0.41396564 0.02354704  1.057799e-02 0.0119799049
[60,] 0.3588491 0.015146604 0.31114736 0.05808157  1.562199e-01 0.0009701975
[61,] 0.3842121 0.021092262 0.14859979 0.02323750  8.578349e-02 0.0085111499
      [,20]       [,21]
 [1,] 0.023156684 0.025899015
 [2,] 0.056981158 0.050350290
 [3,] 0.040377396 0.054358025
 [4,] 0.002912377 0.040327749
 [5,] 0.012865653 0.051937365
 [6,] 0.022140982 0.056566050
 [7,] 0.030274429 0.055151526
 [8,] 0.045767037 0.051110034
 [9,] 0.008259889 0.037288852
[10,] 0.041538338 0.108998487
[11,] 0.026915210 0.023631417
[12,] 0.028883226 0.094347038
[13,] 0.026363876 0.066723467
[14,] 0.015774024 0.005060376
[15,] 0.028293250 0.117705748
[16,] 0.003712323 0.052481762
[17,] 0.046263759 0.141051260
[18,] 0.005017476 0.080968768
[19,] 0.018960848 0.088653032
[20,] 0.032294165 0.120306664
[21,] 0.069898471 0.084595907
[22,] 0.011959843 0.141163216
[23,] 0.012293259 0.084076800
[24,] 0.011030291 0.067493230
[25,] 0.041099973 0.076487962
[26,] 0.050468040 0.003935601
[27,] 0.067503318 0.062943906
[28,] 0.022990221 0.097259399
[29,] 0.002598698 0.049494726
[30,] 0.033149197 0.046515272
[31,] ⋮           ⋮
[32,] 0.011625740 0.051145946
[33,] 0.030493758 0.077522419
[34,] 0.009586534 0.047238559
[35,] 0.032708386 0.053171322
[36,] 0.012606407 0.043568110
[37,] 0.037497388 0.059279681
[38,] 0.042487186 0.102020727
[39,] 0.019866054 0.097701204
[40,] 0.089782963 0.013534919
[41,] 0.040363341 0.038079713
[42,] 0.030884673 0.106476057
[43,] 0.010064836 0.036926587
[44,] 0.021794936 0.032628573
[45,] 0.002685228 0.015842778
[46,] 0.113195077 0.019858104
[47,] 0.026854366 0.064344252
[48,] 0.049963133 0.169746335
[49,] 0.073753214 0.009029226
[50,] 0.105823367 0.068680871
[51,] 0.019791725 0.025483250
[52,] 0.007514846 0.048646817
[53,] 0.068662066 0.012572664
[54,] 0.013023825 0.038187072
[55,] 0.036560989 0.066800301
[56,] 0.019532508 0.050248951
[57,] 0.119588621 0.147330487
[58,] 0.064818151 0.190179440
[59,] 0.026147039 0.033615763
[60,] 0.080925258 0.150360570
[61,] 0.007186949 0.129327029

In [8]:
num_samples = nrow(p_est_draws) # Number of posterior samples
num_included_scenarios = nrow(included_scenarios) #Number of included scenarios to generate I^2 estimates for 
I_2_est_mat = array(-1, dim = c(num_included_scenarios, num_samples)) #Matrix of I^2 estimates (with each posterior sample corresponding to one I^2 estimate)
correction = 0.00001 #To prevent NaN in I2 estimates

#For each row corresponding to an included scenario
for(curr_row_ind in 1:num_included_scenarios){
    curr_row = included_scenarios[curr_row_ind, ]
    curr_scenario = curr_row$Scenario #Name of scenario to retrieve from outcome_df
    curr_scenario_ind = curr_row$ScenarioIndex #Index of Scenario so we know which value of p to get
    curr_outcomes = outcome_df %>% filter(Scenario == curr_scenario) #Get the relevant outcomes that are part of the scenario
    num_outcomes = nrow(curr_outcomes) #Get number of outcomes
    curr_p_vals = p_est_draws[ , curr_scenario_ind] #Get the values of p (column corresponding to the scenario index)
    
    curr_theta_indices = curr_outcomes %>% pull(ThetaIndex) #Get the theta index of each outcome. These should just be from 1:num_outcomes in the order of the outcome_df
    curr_n_vals = curr_outcomes %>% pull(N) #Sample size of each outcome in the given scenario
    curr_theta_vals = theta_est_draws[, curr_theta_indices] #matrix of theta values that match the outcomes for the given scenario
    
    #For each sample, we compute an estimate of I^2 (this means matching indices of p and thetas)
    I_2_est_samples = array(-1, dim = num_samples)
    for(curr_sample_ind in 1:num_samples){
        curr_p = curr_p_vals[curr_sample_ind] #Current p sample from the posterior distribution
        curr_theta = curr_theta_vals[curr_sample_ind, ] #Current theta samples from the posterior distribution
        
        without_het = array(-1, dim = length(num_outcomes)) #Between study variance in the absence of heterogeneity
        with_het = array(-1, dim = length(num_outcomes)) #Between study variance given heterogeneity
        
        for(i in 1:num_outcomes){
            without_het[i] = rbinom(n = 1, size = curr_n_vals[i], prob = curr_p) #For each outcome in the scenario, generate 1 random binomial draw using the outcome's sample size and the pooled estimate

            #We also generate 1 random binomial draw still using the outcome's sample size,
            #but this time using theta as the probability (includes random effect)
            with_het[i] = rbinom(n = 1, size = curr_n_vals[i], prob = curr_theta[i]) 
        }

        #Convert the binomial draws to proportions by dividing by the sample sizes
        without_het_props = without_het / curr_n_vals
        with_het_props = with_het / curr_n_vals

        #Compute the variance between proportions with and without heterogeneity - adding in the correction to both values to prevent divisions by 0 
        #which could occur for scenarios with only a small number of studies and/or smalller sample sizes
        var_het = var(with_het_props) + correction
        var_without_het = var(without_het_props) + correction
        I_2_est_samples[curr_sample_ind] = (var_het - var_without_het) / var_het
    }
    #Set the I^2 estimates for the scenario to the samples computed 
    I_2_est_mat[curr_row_ind, ] = I_2_est_samples
}

In [9]:
#Compute the I^2 estimate for each scenario by taking the median. We replace any values < 0 with 0
#These negative values can occur in scenarios with a small number of studies and/or small samples sizes or those with barely any heterogeneity. 
median_I2 = apply(I_2_est_mat, 1, median)
median_I2[median_I2 < 0] = 0 #Replace negative values with 0 
median_I2

 [1] 0.9134498 0.9609659 0.9965774 0.9993254 0.9715538 0.9031414 0.8933926
 [8] 0.8231186 0.4361909 0.0000000 0.9891310 0.9022885 0.9367085

In [10]:
scenario_I2 = included_scenarios %>% mutate(I2_est = median_I2) 
output = scenario_df %>% left_join(scenario_I2 %>% select(Scenario, I2_est), by = "Scenario")#Create a DataFrame with scenario labels and the I^2 estimates to be output

In [11]:
saveRDS(output, file.path(output_dir, paste0("I2_Estimates_", sev_class_type, ".rds"))) #Save the output to RDS file for use in visualisations